name: Clenup Tailnet

on:
  workflow_dispatch:

  # schedule:
  #   - cron: "0 * * * *" 

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container: ghcr.io/simonhaas/tailscale-node-remover:main
    steps:
    - run: node /app/index.js
