name: Clenup Tailnet using the naked container

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container: ghcr.io/simonhaas/tailscale-node-remover:main
    steps:
    - run: node /app/index.js
    env:
      TS_API_TOKEN: ${{ secrets.TS_API_TOKEN }}
      TS_TAGS: "tag:k8s, tag:k8s-operator"
      TS_TIMEOUT: 60 
