name: Clenup Tailnet

on:
  workflow_dispatch:

  # schedule:
  #   - cron: "0 * * * *" 

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container: ghcr.io/simonhaas/tailscale-node-remover
    steps:
    - run: echo Tailnet is clean again!
