name: Test Docker Action

on:
    workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup Tailnet
        uses: simonhaas/tailscale-node-remover@main
        id: cleanup
        with:
            ts_api_token: ${{ secrets.TS_API_TOKEN }}
      - name: Get the output
        run: echo "OUTPUT ${{ steps.cleanup.outputs.removed_nodes }}"
